import type { ModelCatalogEntry } from './types'

// Curated, hand-tested models. This is the "opposite of whatever string
// happens to be in the config file" — see docs/product-configuration-architecture.md.
// Anything the backend can see that isn't listed here is still usable, just
// surfaced as "experimental" (see configLayer.mergeModelCatalog) instead of
// silently presented as equally trustworthy.
export const SUPPORTED_MODELS: ModelCatalogEntry[] = [
  {
    id: 'phi3:mini',
    displayName: 'Phi-3 Mini',
    provider: 'ollama',
    tier: 'supported',
    sizeParams: '3.8B',
    approxRamGb: 4,
    speed: 'fast',
    quality: 'good',
    capabilities: ['chat'],
    recommendedRoles: ['classifier', 'router'],
  },
  {
    id: 'llama3.2:3b',
    displayName: 'Llama 3.2 3B',
    provider: 'ollama',
    tier: 'supported',
    sizeParams: '3B',
    approxRamGb: 4,
    speed: 'fast',
    quality: 'good',
    capabilities: ['chat'],
    recommendedRoles: ['chat', 'classifier', 'router', 'orchestrator', 'coder', 'planner'],
  },
  {
    id: 'llama3.1:8b',
    displayName: 'Llama 3.1 8B',
    provider: 'ollama',
    tier: 'supported',
    sizeParams: '8B',
    approxRamGb: 8,
    speed: 'balanced',
    quality: 'better',
    capabilities: ['chat', 'reasoning', 'tools'],
    recommendedRoles: ['chat', 'orchestrator', 'planner'],
  },
  {
    id: 'qwen2.5-coder:7b',
    displayName: 'Qwen 2.5 Coder 7B',
    provider: 'ollama',
    tier: 'supported',
    sizeParams: '7B',
    approxRamGb: 8,
    speed: 'balanced',
    quality: 'better',
    capabilities: ['chat', 'coding', 'tools'],
    recommendedRoles: ['coder'],
  },
  {
    id: 'qwen2.5-coder:32b',
    displayName: 'Qwen 2.5 Coder 32B',
    provider: 'ollama',
    tier: 'supported',
    sizeParams: '32B',
    approxRamGb: 24,
    speed: 'slow',
    quality: 'best',
    capabilities: ['chat', 'coding', 'tools'],
    recommendedRoles: ['coder'],
  },
  {
    id: 'llama3.1:70b',
    displayName: 'Llama 3.1 70B',
    provider: 'ollama',
    tier: 'supported',
    sizeParams: '70B',
    approxRamGb: 48,
    speed: 'slow',
    quality: 'best',
    capabilities: ['chat', 'reasoning', 'tools'],
    recommendedRoles: ['chat', 'orchestrator', 'planner'],
  },
  {
    id: 'llava:7b',
    displayName: 'LLaVA 7B',
    provider: 'ollama',
    tier: 'supported',
    sizeParams: '7B',
    approxRamGb: 8,
    speed: 'balanced',
    quality: 'good',
    capabilities: ['chat', 'vision'],
    recommendedRoles: ['vision'],
  },
  {
    id: 'llava:13b',
    displayName: 'LLaVA 13B',
    provider: 'ollama',
    tier: 'supported',
    sizeParams: '13B',
    approxRamGb: 14,
    speed: 'slow',
    quality: 'better',
    capabilities: ['chat', 'vision'],
    recommendedRoles: ['vision'],
  },
  {
    id: 'nomic-embed-text',
    displayName: 'Nomic Embed Text',
    provider: 'ollama',
    tier: 'supported',
    sizeParams: '137M',
    approxRamGb: 1,
    speed: 'fast',
    quality: 'good',
    capabilities: ['embeddings'],
    recommendedRoles: [],
  },
  {
    id: 'mxbai-embed-large',
    displayName: 'MixedBread Embed Large',
    provider: 'ollama',
    tier: 'supported',
    sizeParams: '335M',
    approxRamGb: 2,
    speed: 'fast',
    quality: 'better',
    capabilities: ['embeddings'],
    recommendedRoles: [],
  },
]

export function findCatalogEntry(id: string): ModelCatalogEntry | null {
  return SUPPORTED_MODELS.find((m) => m.id === id) ?? null
}
